/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RelationshipLibrary {
  [k: string]: Relationship;
}
export interface Relationship {
  /**
   * The type of relationship between components.
   */
  relationshipType: string;
  /**
   * The category of the relationship.
   */
  relationshipCategory: 'group' | 'connection';
  /**
   * A description of the relationship.
   */
  description: string;
  [k: string]: unknown;
}
