/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ComponentLibrary {
  [k: string]: Component;
}
export interface Component {
  type: string;
  classification: string;
  description?: string;
  name: string;
  iconUrl: string | null;
  tags: string[];
  properties: {
    [k: string]: {
      name: string;
      description: string;
      type: string;
      config?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
  };
}
